### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style') at AskChatGPTHandler.ts:60:20

### ISSUE THREAD

**Issue by Chernfalin** [debanjandhar12/logseq-chatgpt-plugin#16]
After using for a while, the "ask chatgpt" button disappeared with the following error message: 
"Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style') at AskChatGPTHandler.ts:60:20".

```javascript
// Show button if current page is a ChatGPT page only
            const page = await logseq.Editor.getCurrentPage();
            if (!(page.originalName && (page.properties?.type == "ChatGPT" || page.properties?.type == "[[ChatGPT]]"))) {
                button.style.display = "none";
                window.parent.document.getElementById("main-content-container").removeEventListener("scroll", window.parent.scrollFixForChatGPTPlugin);
                return;
            }
            button.style.display = "block";
```

**Comment by Chernfalin** [comment]
Running normally in logseq 0.9.1.

**Comment by debanjandhar12** [comment]
I have fixed it temporarily by moving the ask chatgpt button to toolbar instead of pagebar. I think pagebar is broken in the new logseq version.
