### ISSUE TITLE
Fail fetch Error in Macbook pro m2

### ISSUE THREAD

**Issue by xx299x** [debanjandhar12/logseq-chatgpt-plugin#3]
api.openai.com/v1/chat/completions:1          Failed to load resource: net::ERR_CONNECTION_CLOSED
AskChatGPTHandler.ts:102 TypeError: Failed to fetch
    at e.<anonymous> (index.js:1:2098)
    at index.js:1:1344
    at Object.next (index.js:1:639)
    at index.js:1:330
    at new Promise (<anonymous>)
    at L (index.js:1:75)
    at e.req (index.js:1:1752)
    at e.stream (index.js:1:2726)
    at Y.askChatGPT (AskChatGPTHandler.ts:182:43)
    at async Y.askChatGPTWrapper (AskChatGPTHandler.ts:86:24)

I use the socks5 proxy in logseq

**Comment by xx299x** [comment]
The problem is Ban IP
